"""empty message

Revision ID: 0c36f45f0763
Revises: 400c45ef8593
Create Date: 2022-08-27 09:35:58.798367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c36f45f0763'
down_revision = '400c45ef8593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('acitve', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('id_product')
    )
    op.create_unique_constraint(None, 'category', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_table('product')
    # ### end Alembic commands ###
