"""empty message

Revision ID: 400c45ef8593
Revises: cf44798bf681
Create Date: 2022-08-27 08:33:47.467676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400c45ef8593'
down_revision = 'cf44798bf681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
