"""empty message

Revision ID: 53f895320a40
Revises: 7e3896dc0cf9
Create Date: 2022-11-12 10:56:49.406749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f895320a40'
down_revision = '7e3896dc0cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredients_product_id_fkey', 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ingredients_product_id_fkey', 'ingredients', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
