"""empty message

Revision ID: 6081cb4b353b
Revises: 34cce9a89fcc
Create Date: 2022-09-22 09:02:30.135952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6081cb4b353b'
down_revision = '34cce9a89fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_allergens')
    # ### end Alembic commands ###
