"""empty message

Revision ID: 863b62455d46
Revises: 6a359824d2ac
Create Date: 2022-08-31 09:05:28.853807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863b62455d46'
down_revision = '6a359824d2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergenos',
    sa.Column('id_alergenos', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_alergenos'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alergenos')
    # ### end Alembic commands ###
