"""empty message

Revision ID: 909501bacb91
Revises: f188396808e6
Create Date: 2022-09-13 17:05:09.890078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909501bacb91'
down_revision = 'f188396808e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergens', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allergens', 'name')
    # ### end Alembic commands ###
