"""empty message

Revision ID: 920a953b7375
Revises: fefb1a52d71b
Create Date: 2022-09-01 14:23:48.877323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920a953b7375'
down_revision = 'fefb1a52d71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_city_key', 'addresses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('addresses_city_key', 'addresses', ['city'])
    # ### end Alembic commands ###
