"""empty message

Revision ID: 9a010a05f229
Revises: 863b62455d46
Create Date: 2022-08-31 09:30:17.593877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a010a05f229'
down_revision = '863b62455d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id_allergens', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_allergens'),
    sa.UniqueConstraint('description')
    )
    op.drop_table('alergenos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergenos',
    sa.Column('id_alergenos', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_alergenos', name='alergenos_pkey'),
    sa.UniqueConstraint('description', name='alergenos_description_key')
    )
    op.drop_table('allergens')
    # ### end Alembic commands ###
