"""empty message

Revision ID: a3358a6a376c
Revises: e52504a42a48
Create Date: 2022-09-15 10:53:42.979373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3358a6a376c'
down_revision = 'e52504a42a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userAllergens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userAllergens',
    sa.Column('allergen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], name='userAllergens_allergen_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userAllergens_user_id_fkey'),
    sa.PrimaryKeyConstraint('allergen_id', 'user_id', name='userAllergens_pkey')
    )
    op.drop_table('user_allergens')
    # ### end Alembic commands ###
