"""empty message

Revision ID: be57e42fd8d7
Revises: 920a953b7375
Create Date: 2022-09-12 17:14:43.021820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be57e42fd8d7'
down_revision = '920a953b7375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens__users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Allergens_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Allergens_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allergens__users')
    # ### end Alembic commands ###
