"""empty message

Revision ID: f188396808e6
Revises: be57e42fd8d7
Create Date: 2022-09-12 17:58:33.380188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f188396808e6'
down_revision = 'be57e42fd8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergens__users', sa.Column('allergens_id', sa.Integer(), nullable=False))
    op.drop_constraint('allergens__users_Allergens_id_fkey', 'allergens__users', type_='foreignkey')
    op.create_foreign_key(None, 'allergens__users', 'allergens', ['allergens_id'], ['id'])
    op.drop_column('allergens__users', 'Allergens_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergens__users', sa.Column('Allergens_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'allergens__users', type_='foreignkey')
    op.create_foreign_key('allergens__users_Allergens_id_fkey', 'allergens__users', 'allergens', ['Allergens_id'], ['id'])
    op.drop_column('allergens__users', 'allergens_id')
    # ### end Alembic commands ###
